name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  ci:
    name: Continuous Integration
    uses: pareshp-org/control-plane/.github/workflows/reusable-ci.yml@main
    with:
      product_id: "product-template"
      environment: "ci"
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
